### ISSUE TITLE
Application using vertigo can not compile under Clojure 1.8.0-alpha4

### ISSUE THREAD

**Issue by blueberry** [ztellman/vertigo#7]
An app that worked with vertigo 1.3.0 and Clojure 1.7.0 causes the following exception in the Clojure compiler:
java.lang.NoClassDefFoundError: IllegalName: compile__stub.vertigo.bytes.vertigo.bytes/ByteSeq, compiling:(vertigo/bytes.clj:90:1)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6894)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6649)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6025)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6343)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6887)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6649)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6025)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5401)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3975)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6885)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6649)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3769)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6889)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6649)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6255)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6887)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6649)
	at clojure.lang.Compiler.compile1(Compiler.java:7483)
	at clojure.lang.Compiler.compile(Compiler.java:7555)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5445.invoke(core.clj:5871)
	at clojure.core$load.invokeStatic(core.clj:5870)
	at clojure.core$load_one.invokeStatic(core.clj:5671)
	at clojure.core$load_one.invoke(core.clj)
	at clojure.core$load_lib$fn__5394.invoke(core.clj:5716)
	at clojure.core$load_lib.invokeStatic(core.clj:5715)
	at clojure.core$load_lib.doInvoke(core.clj)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:635)
	at clojure.core$load_libs.invokeStatic(core.clj:5753)
	at clojure.core$load_libs.doInvoke(core.clj)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:635)
	at clojure.core$require.invokeStatic(core.clj:5775)
	at clojure.core$require.doInvoke(core.clj)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at vertigo.structs$loading__5337__auto____3313.invoke(structs.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3654)
	at clojure.lang.Compiler.compile1(Compiler.java:7488)
	at clojure.lang.Compiler.compile1(Compiler.java:7478)
	at clojure.lang.Compiler.compile(Compiler.java:7555)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5445.invoke(core.clj:5871)
	at clojure.core$load.invokeStatic(core.clj:5870)
	at clojure.core$load_one.invokeStatic(core.clj:5671)
	at clojure.core$load_one.invoke(core.clj)
	at clojure.core$load_lib$fn__5394.invoke(core.clj:5716)
	at clojure.core$load_lib.invokeStatic(core.clj:5715)
	at clojure.core$load_lib.doInvoke(core.clj)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:635)
	at clojure.core$load_libs.invokeStatic(core.clj:5753)
	at clojure.core$load_libs.doInvoke(core.clj)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:635)
	at clojure.core$require.invokeStatic(core.clj:5775)
	at clojure.core$require.doInvoke(core.clj)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at vertigo.core$loading__5337__auto____1375.invoke(core.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3654)
	at clojure.lang.Compiler.compile1(Compiler.java:7488)
	at clojure.lang.Compiler.compile1(Compiler.java:7478)
	at clojure.lang.Compiler.compile(Compiler.java:7555)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5445.invoke(core.clj:5871)
	at clojure.core$load.invokeStatic(core.clj:5870)
	at clojure.core$load_one.invokeStatic(core.clj:5671)
	at clojure.core$load_one.invoke(core.clj)
	at clojure.core$load_lib$fn__5394.invoke(core.clj:5716)
	at clojure.core$load_lib.invokeStatic(core.clj:5715)
	at clojure.core$load_lib.doInvoke(core.clj)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:635)
	at clojure.core$load_libs.invokeStatic(core.clj:5757)
	at clojure.core$load_libs.doInvoke(core.clj)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:635)
	at clojure.core$require.invokeStatic(core.clj:5775)
	at clojure.core$require.doInvoke(core.clj)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at uncomplicate.neanderthal.impl.buffer_block$loading__5337__auto____1373.invoke(buffer_block.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3654)
	at clojure.lang.Compiler.compile1(Compiler.java:7488)
	at clojure.lang.Compiler.compile1(Compiler.java:7478)
	at clojure.lang.Compiler.compile(Compiler.java:7555)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5445.invoke(core.clj:5871)
	at clojure.core$load.invokeStatic(core.clj:5870)
	at clojure.core$load_one.invokeStatic(core.clj:5671)
	at clojure.core$compile$fn__5450.invoke(core.clj:5881)
	at clojure.core$compile.invokeStatic(core.clj:5881)
	at clojure.core$compile.invoke(core.clj)
	at user$eval1022$fn__1029.invoke(form-init6809606777108778687.clj:1)
	at user$eval1022.invokeStatic(form-init6809606777108778687.clj:1)
	at user$eval1022.invoke(form-init6809606777108778687.clj)
	at clojure.lang.Compiler.eval(Compiler.java:6946)
	at clojure.lang.Compiler.eval(Compiler.java:6936)
	at clojure.lang.Compiler.load(Compiler.java:7393)
	at clojure.lang.Compiler.loadFile(Compiler.java:7331)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NoClassDefFoundError: IllegalName: compile__stub.vertigo.bytes.vertigo.bytes/ByteSeq
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:654)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
	at clojure.lang.Compiler$NewInstanceExpr.compileStub(Compiler.java:7913)
	at clojure.lang.Compiler$NewInstanceExpr.build(Compiler.java:7778)
	at clojure.lang.Compiler$NewInstanceExpr$DeftypeParser.parse(Compiler.java:7688)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6887)
	... 130 more
Exception in thread "main" java.lang.NoClassDefFoundError: IllegalName: compile__stub.vertigo.bytes.vertigo.bytes/ByteSeq, compiling:(vertigo/bytes.clj:90:1)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6894)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6649)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6025)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6343)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6887)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6649)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6025)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5401)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3975)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6885)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6649)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3769)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6889)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6649)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6255)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6887)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.analyze(Compiler.java:6649)
	at clojure.lang.Compiler.compile1(Compiler.java:7483)
	at clojure.lang.Compiler.compile(Compiler.java:7555)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5445.invoke(core.clj:5871)
	at clojure.core$load.invokeStatic(core.clj:5870)
	at clojure.core$load_one.invokeStatic(core.clj:5671)
	at clojure.core$load_one.invoke(core.clj)
	at clojure.core$load_lib$fn__5394.invoke(core.clj:5716)
	at clojure.core$load_lib.invokeStatic(core.clj:5715)
	at clojure.core$load_lib.doInvoke(core.clj)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:635)
	at clojure.core$load_libs.invokeStatic(core.clj:5753)
	at clojure.core$load_libs.doInvoke(core.clj)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:635)
	at clojure.core$require.invokeStatic(core.clj:5775)
	at clojure.core$require.doInvoke(core.clj)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at vertigo.structs$loading__5337__auto____3313.invoke(structs.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3654)
	at clojure.lang.Compiler.compile1(Compiler.java:7488)
	at clojure.lang.Compiler.compile1(Compiler.java:7478)
	at clojure.lang.Compiler.compile(Compiler.java:7555)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5445.invoke(core.clj:5871)
	at clojure.core$load.invokeStatic(core.clj:5870)
	at clojure.core$load_one.invokeStatic(core.clj:5671)
	at clojure.core$load_one.invoke(core.clj)
	at clojure.core$load_lib$fn__5394.invoke(core.clj:5716)
	at clojure.core$load_lib.invokeStatic(core.clj:5715)
	at clojure.core$load_lib.doInvoke(core.clj)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:635)
	at clojure.core$load_libs.invokeStatic(core.clj:5753)
	at clojure.core$load_libs.doInvoke(core.clj)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:635)
	at clojure.core$require.invokeStatic(core.clj:5775)
	at clojure.core$require.doInvoke(core.clj)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at vertigo.core$loading__5337__auto____1375.invoke(core.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3654)
	at clojure.lang.Compiler.compile1(Compiler.java:7488)
	at clojure.lang.Compiler.compile1(Compiler.java:7478)
	at clojure.lang.Compiler.compile(Compiler.java:7555)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5445.invoke(core.clj:5871)
	at clojure.core$load.invokeStatic(core.clj:5870)
	at clojure.core$load_one.invokeStatic(core.clj:5671)
	at clojure.core$load_one.invoke(core.clj)
	at clojure.core$load_lib$fn__5394.invoke(core.clj:5716)
	at clojure.core$load_lib.invokeStatic(core.clj:5715)
	at clojure.core$load_lib.doInvoke(core.clj)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:635)
	at clojure.core$load_libs.invokeStatic(core.clj:5757)
	at clojure.core$load_libs.doInvoke(core.clj)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:635)
	at clojure.core$require.invokeStatic(core.clj:5775)
	at clojure.core$require.doInvoke(core.clj)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at uncomplicate.neanderthal.impl.buffer_block$loading__5337__auto____1373.invoke(buffer_block.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3654)
	at clojure.lang.Compiler.compile1(Compiler.java:7488)
	at clojure.lang.Compiler.compile1(Compiler.java:7478)
	at clojure.lang.Compiler.compile(Compiler.java:7555)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5445.invoke(core.clj:5871)
	at clojure.core$load.invokeStatic(core.clj:5870)
	at clojure.core$load_one.invokeStatic(core.clj:5671)
	at clojure.core$compile$fn__5450.invoke(core.clj:5881)
	at clojure.core$compile.invokeStatic(core.clj:5881)
	at clojure.core$compile.invoke(core.clj)
	at user$eval1022$fn__1029.invoke(form-init6809606777108778687.clj:1)
	at user$eval1022.invokeStatic(form-init6809606777108778687.clj:1)
	at user$eval1022.invoke(form-init6809606777108778687.clj)
	at clojure.lang.Compiler.eval(Compiler.java:6946)
	at clojure.lang.Compiler.eval(Compiler.java:6936)
	at clojure.lang.Compiler.load(Compiler.java:7393)
	at clojure.lang.Compiler.loadFile(Compiler.java:7331)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NoClassDefFoundError: IllegalName: compile__stub.vertigo.bytes.vertigo.bytes/ByteSeq
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:654)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
	at clojure.lang.Compiler$NewInstanceExpr.compileStub(Compiler.java:7913)
	at clojure.lang.Compiler$NewInstanceExpr.build(Compiler.java:7778)
	at clojure.lang.Compiler$NewInstanceExpr$DeftypeParser.parse(Compiler.java:7688)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6887)

**Comment by ztellman** [comment]
If you target `[potemkin "0.4.1"]` explicitly, it'll fix that.  I'll leave this issue open until I've cut a new version that uses the newer Potemkin.

**Comment by ztellman** [comment]
This is fixed in 0.1.4.
